/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolsystem;

import com.sun.glass.events.KeyEvent;
import java.awt.*;
import java.awt.event.WindowEvent;
import java.sql.*;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.util.*;
import javax.swing.JTable;

/**
 *
 * @author Keagan Nigel Gonsalves
 */
public class TeacherInfo extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    /**
     * Creates new form TeacherInfo
     */
    public TeacherInfo() {
        initComponents();
        conn=javaconnect.ConnectDb();
        Update_Table();
        Fillcombo();
        Date();
    }
    
    public void Date() {
    Calendar cal = new GregorianCalendar();
    int month = cal.get(Calendar.MONTH);
    int year = cal.get(Calendar.YEAR);
    int day = cal.get(Calendar.DAY_OF_MONTH);
    menu_date.setText("Date: "+year+"/"+(month+1)+"/"+day);
    
    int second = cal.get(Calendar.SECOND);
    int minute = cal.get(Calendar.MINUTE);
    int hour = cal.get(Calendar.HOUR);
    menu_time.setText("Time: "+hour+":"+minute+":"+second);
    }
    
    public void close(){
        
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    private void Update_Table(){
        try{
        String sql = "select teacherid,name,surname,age,division from Teacherinfo";
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        tbl_teacherinfo.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,"unable to update the table");
        } finally {
            try{
            rs.close();
            pst.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error closing database connection");    
                }
        }
    }
    
    private void Fillcombo(){
        try{
        String sql = "select * from Teacherinfo";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        
        while(rs.next()){
        String name = rs.getString("name");
        combobox_search.addItem(name);
        
        }
        
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Search cannot be performed on the combo box");
        } finally {
            try{
            rs.close();
            pst.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error closing database connection");    
                }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_teacherinfo = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        cmd_close = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_division = new javax.swing.JTextField();
        txt_teacherid = new javax.swing.JTextField();
        txt_age = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_surname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cmd_save = new javax.swing.JButton();
        cmd_update = new javax.swing.JButton();
        cmd_delete = new javax.swing.JButton();
        cmd_new = new javax.swing.JButton();
        cmd_clear = new javax.swing.JButton();
        cmd_print = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        combobox_search = new javax.swing.JComboBox<>();
        txt_search = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_file = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        menu_edit = new javax.swing.JMenu();
        menu_date = new javax.swing.JMenu();
        menu_time = new javax.swing.JMenu();
        menu_help = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbl_teacherinfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_teacherinfo.setToolTipText("All Teachers saved on the system");
        tbl_teacherinfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_teacherinfoMouseClicked(evt);
            }
        });
        tbl_teacherinfo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbl_teacherinfoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_teacherinfo);

        jToolBar1.setRollover(true);

        cmd_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolsystem/Button-Close-icon.png"))); // NOI18N
        cmd_close.setText("CLOSE");
        cmd_close.setFocusable(false);
        cmd_close.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmd_close.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmd_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_closeActionPerformed(evt);
            }
        });
        jToolBar1.add(cmd_close);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Teacher Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(255, 51, 51))); // NOI18N

        jLabel4.setText("Age:");

        txt_division.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_division.setToolTipText("Enter division.");

        txt_teacherid.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_teacherid.setText(" ");
        txt_teacherid.setToolTipText("Enter teacherid.");

        txt_age.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_age.setToolTipText("Enter age.");

        jLabel1.setText("Teacher Id:");

        txt_name.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_name.setForeground(new java.awt.Color(204, 0, 0));
        txt_name.setText(" ");
        txt_name.setToolTipText("Enter name.");

        jLabel3.setText("Surname:");

        jLabel5.setText("Division:");

        txt_surname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_surname.setText(" ");
        txt_surname.setToolTipText("Enter surname.");

        jLabel2.setText("Name:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_name, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(txt_teacherid, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_age)
                    .addComponent(txt_surname, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_division, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txt_name, txt_surname});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_teacherid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txt_surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_division, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txt_name, txt_surname});

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buttons", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(51, 153, 255))); // NOI18N

        cmd_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolsystem/save.png"))); // NOI18N
        cmd_save.setText("Save");
        cmd_save.setToolTipText("Save new Information to the database.");
        cmd_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_saveActionPerformed(evt);
            }
        });

        cmd_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolsystem/update.png"))); // NOI18N
        cmd_update.setText("Update");
        cmd_update.setToolTipText("Update the records.");
        cmd_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_updateActionPerformed(evt);
            }
        });

        cmd_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolsystem/delete.png"))); // NOI18N
        cmd_delete.setText("Delete");
        cmd_delete.setToolTipText("Delete the teacher's informationf from the database.");
        cmd_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_deleteActionPerformed(evt);
            }
        });

        cmd_new.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolsystem/new.png"))); // NOI18N
        cmd_new.setText("Student Info");
        cmd_new.setToolTipText("Go to the Student Information Database.");
        cmd_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_newActionPerformed(evt);
            }
        });

        cmd_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolsystem/Clear.png"))); // NOI18N
        cmd_clear.setText("Clear");
        cmd_clear.setToolTipText("Clear details selected.");
        cmd_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_clearActionPerformed(evt);
            }
        });

        cmd_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolsystem/print.png"))); // NOI18N
        cmd_print.setText("Print");
        cmd_print.setToolTipText("Print all the Teacher's information.");
        cmd_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_printActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmd_clear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmd_new)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmd_save)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmd_update)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmd_delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmd_print)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmd_save)
                    .addComponent(cmd_new)
                    .addComponent(cmd_delete)
                    .addComponent(cmd_update)
                    .addComponent(cmd_clear)
                    .addComponent(cmd_print))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 102, 255))); // NOI18N

        combobox_search.setToolTipText("Name combobox");
        combobox_search.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                combobox_searchPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        txt_search.setBackground(new java.awt.Color(102, 255, 204));
        txt_search.setToolTipText("Search using Teacherid, name, surname....");
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(combobox_search, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(combobox_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menu_file.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolsystem/new.png"))); // NOI18N
        jMenuItem1.setText("New");
        menu_file.add(jMenuItem1);
        menu_file.add(jSeparator1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolsystem/save.png"))); // NOI18N
        jMenuItem2.setText("Save");
        menu_file.add(jMenuItem2);
        menu_file.add(jSeparator2);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolsystem/print.png"))); // NOI18N
        jMenuItem4.setText("Print");
        menu_file.add(jMenuItem4);
        menu_file.add(jSeparator3);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolsystem/Button-Close-icon.png"))); // NOI18N
        jMenuItem3.setText("Close");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menu_file.add(jMenuItem3);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolsystem/exit.png"))); // NOI18N
        jMenuItem7.setText("Exit");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        menu_file.add(jMenuItem7);

        jMenuBar1.add(menu_file);

        menu_edit.setText("Edit");
        jMenuBar1.add(menu_edit);

        menu_date.setText("Date");
        jMenuBar1.add(menu_date);

        menu_time.setText("Time");
        jMenuBar1.add(menu_time);

        menu_help.setText("Help");

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("About");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menu_help.add(jMenuItem5);
        menu_help.add(jSeparator4);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Help");
        menu_help.add(jMenuItem6);

        jMenuBar1.add(menu_help);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(1, 1, 1))))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_teacherinfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_teacherinfoMouseClicked
        // TODO add your handling code here:
        try{
            int row = tbl_teacherinfo.getSelectedRow();
            String Table_Click = (tbl_teacherinfo.getModel().getValueAt(row,0).toString());
            String sql="select * from Teacherinfo where teacherid="+Table_Click+" ";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                
            String add1 = rs.getString("teacherid");
            txt_teacherid.setText(add1);
            String add2 = rs.getString("name"); 
            txt_name.setText(add2);
            String add3 = rs.getString("surname");
            txt_surname.setText(add3);
            String add4 = rs.getString("age");
            txt_age.setText(add4);
            String add5 = rs.getString("division"); 
            txt_division.setText(add5);
            
            int age= Integer.parseInt(add4);
            if(age>=45){
                txt_age.setBackground(Color.red);
                txt_age.setForeground(Color.BLACK);
            }
            else{
                txt_age.setBackground(Color.GREEN);
                txt_age.setForeground(Color.darkGray);
            }
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,"The item cannot be selected from the list.");
        }
    }//GEN-LAST:event_tbl_teacherinfoMouseClicked

    private void combobox_searchPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_combobox_searchPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        String tmp = (String) combobox_search.getSelectedItem();
        String sql = "select * from Teacherinfo where name=?";
        try{
            pst=conn.prepareStatement(sql);
            pst.setString(1, tmp);
            rs=pst.executeQuery();
            if(rs.next()){
            String add1 = rs.getString("teacherid");
            txt_teacherid.setText(add1);
            String add2 = rs.getString("name"); 
            txt_name.setText(add2);
            String add3 = rs.getString("surname");
            txt_surname.setText(add3);
            String add4 = rs.getString("age");
            txt_age.setText(add4);
            String add5 = rs.getString("division"); 
            txt_division.setText(add5);
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Name cannot be searched");
        } finally {
            try{
              rs.close();
              pst.close();
            }
            catch(Exception e){
              JOptionPane.showMessageDialog(null,e);   
            }
        }
    }//GEN-LAST:event_combobox_searchPopupMenuWillBecomeInvisible

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void cmd_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_closeActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_cmd_closeActionPerformed

    private void cmd_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_saveActionPerformed
        // TODO add your handling code here:
        try{
            String sql ="insert into Teacherinfo (teacherid,name,surname,age,division) values (?,?,?,?,?)";
            pst=conn.prepareStatement(sql);
            pst.setString(1, txt_teacherid.getText());
            pst.setString(2, txt_name.getText());
            pst.setString(3, txt_surname.getText());
            pst.setString(4, txt_age.getText());
            pst.setString(5, txt_division.getText());
            
            pst.execute();
            
            JOptionPane.showMessageDialog(null,"Saved.");
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Details not saved.");
            
        } finally {
            try{
              rs.close();
              pst.close();
            }
            catch(Exception e){
               JOptionPane.showMessageDialog(null,e); 
            }
        }
        Update_Table();
    }//GEN-LAST:event_cmd_saveActionPerformed

    private void cmd_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_newActionPerformed
        close();
        StudentInfo s= new StudentInfo();
        s.setVisible(true);
    }//GEN-LAST:event_cmd_newActionPerformed

    private void cmd_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_deleteActionPerformed
        // TODO add your handling code here:
        int p = JOptionPane.showConfirmDialog(null, "Do you really want to delete","Delete",JOptionPane.YES_NO_OPTION);
        if(p==0){
        String sql="delete from Teacherinfo where teacherid=?";
        try{
        pst=conn.prepareStatement(sql);
        
        pst.setString(1,txt_teacherid.getText());
        
        pst.execute();
        
        JOptionPane.showMessageDialog(null, "Deleted.");
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Details cannot be deleted.");
        } finally {
            try{
              rs.close();
              pst.close();
            }
            catch(Exception e){
               JOptionPane.showMessageDialog(null,e); 
            }
        }
        Update_Table();
        }
    }//GEN-LAST:event_cmd_deleteActionPerformed

    private void cmd_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_updateActionPerformed
        // TODO add your handling code here:
        try{
        int row = tbl_teacherinfo.getSelectedRow();             
            String tableclick =(tbl_teacherinfo.getModel().getValueAt(row, 0).toString());             
            String value1=txt_teacherid.getText();             
            String value2=txt_name.getText();             
            String value3=txt_surname.getText();             
            String value4=txt_age.getText();             
            String value5=txt_division.getText(); 
           
            
            String sql ="update Teacherinfo set teacherid='"+value1+"', name='"+value2+"',surname='"+value3+"',age='"+value4+"',division='"+value5+"'where teacherid ='"+tableclick+"'";             
            pst=conn.prepareStatement(sql);             
            pst.execute();             
            JOptionPane.showMessageDialog(null, "Updated.");     
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Details cannot be updated.");
        } finally {
            try{
              rs.close();
              pst.close();
            }
            catch(Exception e){
               JOptionPane.showMessageDialog(null,e); 
            }
        }
        Update_Table();
    }//GEN-LAST:event_cmd_updateActionPerformed

    private void cmd_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_clearActionPerformed
        // TODO add your handling code here:
        txt_teacherid.setText("");
        txt_name.setText("");
        txt_surname.setText("");
        txt_age.setText("");
        txt_division.setText("");     
    }//GEN-LAST:event_cmd_clearActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        try{
            String sql = "select * from Teacherinfo where name =?";
            
            pst = conn.prepareStatement(sql);
            pst.setString(1,txt_search.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                String add1 = rs.getString("teacherid");
                txt_teacherid.setText(add1);
                String add2 = rs.getString("name");
                txt_name.setText(add2);
                String add3 = rs.getString("surname");
                txt_surname.setText(add3);
                String add4 = rs.getString("age");
                txt_age.setText(add4);
                String add5 = rs.getString("division");
                txt_division.setText(add5);
                
            }
            
            
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Teacher name cannot be found.");
        } finally {
            try{
              rs.close();
              pst.close();
            }
            catch(Exception e){
               JOptionPane.showMessageDialog(null,e); 
            }
        }
        
        try{
            String sql = "select * from Teacherinfo where teacherid=?";
            
            pst = conn.prepareStatement(sql);
            pst.setString(1,txt_search.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                String add1 = rs.getString("teacherid");
                txt_teacherid.setText(add1);
                String add2 = rs.getString("name");
                txt_name.setText(add2);
                String add3 = rs.getString("surname");
                txt_surname.setText(add3);
                String add4 = rs.getString("age");
                txt_age.setText(add4);
                String add5 = rs.getString("division");
                txt_division.setText(add5);
            }
            
            
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Teacher Id cannot be found.");
        } finally {
            try{
              rs.close();
              pst.close();
            }
            catch(Exception e){
               JOptionPane.showMessageDialog(null,e); 
            }
        }
        
        try{
            String sql = "select * from Teacherinfo where surname=?";
            
            pst = conn.prepareStatement(sql);
            pst.setString(1,txt_search.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                String add1 = rs.getString("teacherid");
                txt_teacherid.setText(add1);
                String add2 = rs.getString("name");
                txt_name.setText(add2);
                String add3 = rs.getString("surname");
                txt_surname.setText(add3);
                String add4 = rs.getString("age");
                txt_age.setText(add4);
                String add5 = rs.getString("division");
                txt_division.setText(add5);
            }
            
            
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Teacher surname cannot be found.");
        } finally {
            try{
              rs.close();
              pst.close();
            }
            catch(Exception e){
               JOptionPane.showMessageDialog(null,e); 
            }
        }   
    }//GEN-LAST:event_txt_searchKeyReleased

    private void tbl_teacherinfoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_teacherinfoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_DOWN || evt.getKeyCode()==KeyEvent.VK_UP){
         try{
            int row = tbl_teacherinfo.getSelectedRow();
            String Table_click = (tbl_teacherinfo.getModel().getValueAt(row,0).toString());
            String sql = "select * from Teacherinfo where teacherid ='" +Table_click+ "' ";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            if(rs.next()){
                String add1 = rs.getString("teacherid");
                txt_teacherid.setText(add1);
                String add2 = rs.getString("name");
                txt_name.setText(add2);
                String add3 = rs.getString("surname");
                txt_surname.setText(add3);
                String add4 = rs.getString("age");
                txt_age.setText(add4);
                String add5 = rs.getString("division");
                txt_division.setText(add5);
            }
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        } 
         
        }
    }//GEN-LAST:event_tbl_teacherinfoKeyPressed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
         try{
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+"C:\\Users\\user\\Documents\\Keagan CV update final 2016.pdf");
        } catch(Exception ex){
          JOptionPane.showMessageDialog(null,ex);  
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void cmd_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_printActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("TEACHER'S INFORMATION REPORT");
        
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        
        try{
            
            tbl_teacherinfo.print(JTable.PrintMode.NORMAL, header, footer);
            
        } catch(Exception ex){
            System.err.format("Cannot print %s%n",ex.getMessage());
        }
    }//GEN-LAST:event_cmd_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmd_clear;
    private javax.swing.JButton cmd_close;
    private javax.swing.JButton cmd_delete;
    private javax.swing.JButton cmd_new;
    private javax.swing.JButton cmd_print;
    private javax.swing.JButton cmd_save;
    private javax.swing.JButton cmd_update;
    private javax.swing.JComboBox<String> combobox_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu menu_date;
    private javax.swing.JMenu menu_edit;
    private javax.swing.JMenu menu_file;
    private javax.swing.JMenu menu_help;
    private javax.swing.JMenu menu_time;
    private javax.swing.JTable tbl_teacherinfo;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_division;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_surname;
    private javax.swing.JTextField txt_teacherid;
    // End of variables declaration//GEN-END:variables
}
